rebazer:
  # Workspace Directory for checkouts, optional.
  #workspace: ./rebazer-workspace

  # Number of rebases before git garbage collection, optional.
  #garbageCollectionCountdown: 20

  # Delay between each polling interval, optional.
  #pollInterval: 60
  
  # Regex to blacklist branch names that should not be processed, optional.
  #branchBlacklist: ^(main|master|develop|release|hotfix).*
  
  hosts:
  # Repo type, possible values GITHUB or BITBUCKET.
  - type: BITBUCKET

    # optional, default is type-dependent (github.com, bitbucket.org; resp. api.github.com, api.bitbucket.org).
    #gitHost: https://bitbucket.org/
    #apiHost: https://api.bitbucket.org/

    teams:
    - name: your_company
      user: service_user # optional value, default is $name
      pass: dont_use_this_pass_at_home
      repos:
      - name: the_repo_name
        mainBranch: develop # optional value, default is "main"
      - name: other_repo
        mainBranch: trunk

  - type: GITHUB
    teams:
    - name: your_company
      pass: dont_use_this_pass_at_home
      repos:
      - name: foo
